os:
- linux
- osx
language: generic
sudo: required
dist: trusty
osx_image: xcode10
install:
- eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
script:
- swift build

env:
- SWIFT_VERSION=4.2-SNAPSHOT-2018-10-03-a
